### ISSUE TITLE
Option to produce splitted arguments array (as in pre-0.9.5)

### ISSUE THREAD

**Issue by Artalus** [nickdiego/compiledb#51]
I used `compiledb` for a while to analyze Makefiles produced by our legacy build system. It was very convenient since `compile_commands.json` file contained separate field `arguments: []` which I could then grep using `jq`. After recent update `0.9.2 -> 0.9.7` my scripts broke down since now `compiledb` just copies whole long compile command into a single `command` field. It would be nice to have an option to add `arguments` array to the output.

**Comment by nickdiego** [comment]
Hi @Artalus , Thanks for reporting this.
Could you please test locally with the latest master.

**Comment by nickdiego** [comment]
Also, note that several improvements/features/changes have been implemented since version 0.9.2, for example:
- By default, run in incremental mode (i.e: Updates the current `compile_commands.json` if it exists (unless `-f` is used) instead of rewriting it entirely always, this is particularly useful when running non clean builds with changes in flags/source files, so the `compiledb` is almost(?) ready to be used as a real make wrapper.
- Much better parsing logic (using a bash lexer internally to extract build commands even from quite complex bash expressions, e.g: conditionals, substitution cmds, etc)
- Better handling of compiler wrappers (removing them from final build commands)
- Finally working well with autotools-based build systems (tested with bitcoin core build system, for example)
- By default, it runs in what we called a `strict` mode, which ignore source files which do not exist in the file system (If desired one can disable those checkings using `-S` option, useful for example when processing build logs where the actual code base is not on the host's file system.

**Comment by Artalus** [comment]
Thank you, it works fine now. Only I thought the joined `command` string was considered a feature, not a regression that should be removed completely, but this one is up to you and clang-tools compliance :)
